### ISSUE TITLE
CI for slides is failing

### ISSUE THREAD

**Issue by malvikasharan** [jupytercon/jupyterbook-with-turing-way#3]
@ggorman can you please have a look why CI in this repo is failing? We don’t have currently any slides and the original file In the slides folder has been reverted to how it was.

**Comment by martinagvilas** [comment]
@malvikasharan I think it is because we removed jupytext from the requirements.txt. I will add it and see if it keeps failing.

**Comment by martinagvilas** [comment]
It seemed to be that! Closing the issue since it was solved
