### ISSUE TITLE
Suggestion from JupyterCon team to make some changes to the notebook

### ISSUE THREAD

**Issue by malvikasharan** [jupytercon/jupyterbook-with-turing-way#5]
- [ ] You have included links in the notebooks to the videos on your YouTube channel. Please remove these. We are creating an online course, which has a native video viewer, and we will embed the videos in the learning sequences (from the JupyterCon YouTube channel). If you have links out to YouTube, you will send participants out of the platform, and break the consistent experience.
- [ ] You have emojis on the section headings. Please remove these. (You can go ahead and add an emoji below the heading, instead, if you want.) We are using the headings as string markers to delimit chunks of notebooks that are displayed in the online learning sequence. The logic of the Jupyter integration in the course platform needs ASCII-only in headings.
- [ ] Any images included in markdown cells need to be added via <img> </img> HTML tags, instead of ![ ] markdown embed. — We forgot to tell everybody about this, sorry! — This is needed for the Jupyter viewer integration which parses image embeds and pre-pends the raw URL of the image location.
- [ ] You have links at the bottom of the notebooks to go to the “Next Module.” Please remove these. Again, the notebooks will be used as source material for the learning sequences in the course platform (without duplication: they are pulled dynamically from URL and converted to HTML on the fly with nbconvert). The platform has built-in “Next” buttons to go from one section to another.
- [ ] Note that the JupyterCon platform will include a JupyterHub server, connected to the course platform via SSO. Participants will be able to launch a given notebook in interactive session, in an iframe or new tab. They will also be able to launch a Binder session with all the notebooks, using the requirements.txt in the root of your repository. Thus, the explanation about setup is unnecessary and could confuse people. We can skip this in the course (just not display those cells), but please be aware of this, for your planning.

**Comment by martinagvilas** [comment]
Hey @malvikasharan! Have you started working on these already? I did some minor typo changes yesterday, so if you haven't it's better I push that first so we don't get merge conflicts.

**Comment by malvikasharan** [comment]
I will start on this later today, and ping you to make sure that I pull all changes locally before that.

**Comment by martinagvilas** [comment]
Awesome, I'll merge the small changes before that then

**Comment by martinagvilas** [comment]
@malvikasharan do you want me to address points 1 to 4 when addressing #7 ?  It should be super fast and this way we completely avoid merge conflicts

**Comment by malvikasharan** [comment]
That would be great. I am in meetings back to back until 5:00 pm :/

**Comment by martinagvilas** [comment]
@malvikasharan have a good rest from the computer after that! I'll take care of it

**Comment by malvikasharan** [comment]
Thanks a million. You rock! 🎸
